name: storybook
description: "Список кастомных компонентов"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
resolution: workspace
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui_kit
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

